# This file configures character that are like letters and should be replaced in the word filter
# Use lowcase strings to indicate the letterlike characters with space separated values

a: '@'
b: 'l3 i3'
c: 'รง ('
d:
e: '3'
f: 'ph'
g: '6'
h:
i: 'l ! 1'
j:
k:
l: '1 ! i'
m:
n:
o: '0'
p:
q: '9'
r:
s: '$ 5'
t: '7'
u:
v:
w: 'vv'
x: '><'
y:
z: '2'
